name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      # এখানে প্রজেক্টের নাম ছোট হাতের 'acc' নির্দিষ্ট করে দেওয়া হয়েছে
      - name: Create Missing Files
        run: flutter create --project-name=acc --platforms android .

      - name: Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Final-App
          path: build/app/outputs/flutter-apk/app-release.apk
